### PR TITLE
Add convenience web starter

### PR DESCRIPTION
**Pull request by geoand**
The starter includes both the Zipkin Tracer auto-configuration code
as well as OpenTracing's Spring web auto-configuration

### CODE REVIEW

**Review by pavolloffay — APPROVED** [review]
LGTM, could you please submit also all-in-one

**Comment by geoand** [comment]
All-in-one? The new starter contains Zipkin and web autoconfiguration.
What else are you looking for?

**Comment by pavolloffay** [comment]
I mean spring cloud instrumentation which pulls in different starters not only web

**Comment by geoand** [comment]
Yes, I will do that most likely next week 😀

**Pull request merged**
